#!/bin/bash

infile="mouse-extract.h5"
outfile="mouse-extract.h5"
ncpu="8"
dataname="images"

while getopts "f:o:n:" flag; do
  case "${flag}" in
    f) infile="${OPTARG}";;
    o) outfile="${OPTARG}";;
    n) ncpu="${OPTARG}";;
    *) echo "Fuck you you piece of shit";;
  esac
done

moseq apply-pca "${infile}" "${outfile}" --raw-data-name "${dataname}" --n-cpu "${ncpu}"
