_internal.classic_mode: false
agg.path.chunksize: 0
animation.avconv_args: []
animation.avconv_path: avconv
animation.bitrate: -1
animation.codec: h264
animation.convert_args: []
animation.convert_path: convert
animation.embed_limit: 20.0
animation.ffmpeg_args: []
animation.ffmpeg_path: ffmpeg
animation.frame_format: png
animation.html: none
animation.html_args: []
animation.writer: ffmpeg
axes.autolimit_mode: data
axes.axisbelow: line
axes.edgecolor: white
axes.facecolor: '#212121'
axes.formatter.limits: [-7, 7]
axes.formatter.min_exponent: 0
axes.formatter.offset_threshold: 4
axes.formatter.use_locale: false
axes.formatter.use_mathtext: false
axes.formatter.useoffset: true
axes.grid: false
axes.grid.axis: both
axes.grid.which: major
axes.hold: null
axes.labelcolor: white
axes.labelpad: 4.0
axes.labelsize: medium
axes.labelweight: normal
axes.linewidth: 0.8
axes.prop_cycle: !!python/object:cycler.Cycler
  _keys: !!set {color: null}
  _left:
  - {color: '#8dd3c7'}
  - {color: '#feffb3'}
  - {color: '#bfbbd9'}
  - {color: '#fa8174'}
  - {color: '#81b1d2'}
  - {color: '#fdb462'}
  - {color: '#b3de69'}
  - {color: '#bc82bd'}
  - {color: '#ccebc4'}
  - {color: '#ffed6f'}
  _op: null
  _right: null
axes.spines.bottom: true
axes.spines.left: true
axes.spines.right: true
axes.spines.top: true
axes.titlepad: 6.0
axes.titlesize: large
axes.titleweight: normal
axes.unicode_minus: true
axes.xmargin: 0.05
axes.ymargin: 0.05
axes3d.grid: true
backend: Qt5Agg
backend.qt4: null
backend.qt5: null
backend_fallback: true
boxplot.bootstrap: null
boxplot.boxprops.color: k
boxplot.boxprops.linestyle: '-'
boxplot.boxprops.linewidth: 1.0
boxplot.capprops.color: k
boxplot.capprops.linestyle: '-'
boxplot.capprops.linewidth: 1.0
boxplot.flierprops.color: k
boxplot.flierprops.linestyle: none
boxplot.flierprops.linewidth: 1.0
boxplot.flierprops.marker: o
boxplot.flierprops.markeredgecolor: k
boxplot.flierprops.markerfacecolor: none
boxplot.flierprops.markersize: 6.0
boxplot.meanline: false
boxplot.meanprops.color: C2
boxplot.meanprops.linestyle: --
boxplot.meanprops.linewidth: 1.0
boxplot.meanprops.marker: ^
boxplot.meanprops.markeredgecolor: C2
boxplot.meanprops.markerfacecolor: C2
boxplot.meanprops.markersize: 6.0
boxplot.medianprops.color: C1
boxplot.medianprops.linestyle: '-'
boxplot.medianprops.linewidth: 1.0
boxplot.notch: false
boxplot.patchartist: false
boxplot.showbox: true
boxplot.showcaps: true
boxplot.showfliers: true
boxplot.showmeans: false
boxplot.vertical: true
boxplot.whiskerprops.color: k
boxplot.whiskerprops.linestyle: '-'
boxplot.whiskerprops.linewidth: 1.0
boxplot.whiskers: 1.5
contour.corner_mask: true
contour.negative_linestyle: dashed
datapath: /Users/wgillis/anaconda/envs/py3/lib/python3.6/site-packages/matplotlib/mpl-data
date.autoformatter.day: '%Y-%m-%d'
date.autoformatter.hour: '%m-%d %H'
date.autoformatter.microsecond: '%M:%S.%f'
date.autoformatter.minute: '%d %H:%M'
date.autoformatter.month: '%Y-%m'
date.autoformatter.second: '%H:%M:%S'
date.autoformatter.year: '%Y'
docstring.hardcopy: false
errorbar.capsize: 0.0
examples.directory: ''
figure.autolayout: false
figure.constrained_layout.h_pad: 0.04167
figure.constrained_layout.hspace: 0.02
figure.constrained_layout.use: false
figure.constrained_layout.w_pad: 0.04167
figure.constrained_layout.wspace: 0.02
figure.dpi: 200.0
figure.edgecolor: black
figure.facecolor: '#212121'
figure.figsize: [6.4, 4.8]
figure.frameon: true
figure.max_open_warning: 20
figure.subplot.bottom: 0.11
figure.subplot.hspace: 0.2
figure.subplot.left: 0.125
figure.subplot.right: 0.9
figure.subplot.top: 0.88
figure.subplot.wspace: 0.2
figure.titlesize: large
figure.titleweight: normal
font.cursive: [Apple Chancery, Textile, Zapf Chancery, Sand, Script MT, Felipa, cursive]
font.family: [sans-serif]
font.fantasy: [Comic Sans MS, Chicago, Charcoal, ImpactWestern, Humor Sans, xkcd,
  fantasy]
font.monospace: [DejaVu Sans Mono, Bitstream Vera Sans Mono, Computer Modern Typewriter,
  Andale Mono, Nimbus Mono L, Courier New, Courier, Fixed, Terminal, monospace]
font.sans-serif: [DejaVu Sans, Bitstream Vera Sans, Computer Modern Sans Serif, Lucida
    Grande, Verdana, Geneva, Lucid, Arial, Helvetica, Avant Garde, sans-serif]
font.serif: [DejaVu Serif, Bitstream Vera Serif, Computer Modern Roman, New Century
    Schoolbook, Century Schoolbook L, Utopia, ITC Bookman, Bookman, Nimbus Roman No9
    L, Times New Roman, Times, Palatino, Charter, serif]
font.size: 12.0
font.stretch: normal
font.style: normal
font.variant: normal
font.weight: normal
grid.alpha: 1.0
grid.color: white
grid.linestyle: '-'
grid.linewidth: 0.8
hatch.color: k
hatch.linewidth: 1.0
hist.bins: 20
image.aspect: auto
image.cmap: magma
image.composite_image: true
image.interpolation: nearest
image.lut: 256
image.origin: upper
image.resample: true
interactive: false
keymap.all_axes: [a]
keymap.back: [left, c, backspace]
keymap.forward: [right, v]
keymap.fullscreen: [f, ctrl+f]
keymap.grid: [g]
keymap.grid_minor: [G]
keymap.home: [h, r, home]
keymap.pan: [p]
keymap.quit: [ctrl+w, cmd+w, q]
keymap.quit_all: [W, cmd+W, Q]
keymap.save: [s, ctrl+s]
keymap.xscale: [k, L]
keymap.yscale: [l]
keymap.zoom: [o]
legend.borderaxespad: 0.5
legend.borderpad: 0.4
legend.columnspacing: 2.0
legend.edgecolor: '0.8'
legend.facecolor: inherit
legend.fancybox: true
legend.fontsize: medium
legend.framealpha: 0.8
legend.frameon: true
legend.handleheight: 0.7
legend.handlelength: 2.0
legend.handletextpad: 0.8
legend.labelspacing: 0.5
legend.loc: best
legend.markerscale: 1.0
legend.numpoints: 1
legend.scatterpoints: 1
legend.shadow: false
lines.antialiased: true
lines.color: white
lines.dash_capstyle: butt
lines.dash_joinstyle: round
lines.dashdot_pattern: [6.4, 1.6, 1.0, 1.6]
lines.dashed_pattern: [3.7, 1.6]
lines.dotted_pattern: [1.0, 1.65]
lines.linestyle: '-'
lines.linewidth: 1.5
lines.marker: None
lines.markeredgewidth: 1.0
lines.markersize: 6.0
lines.scale_dashes: true
lines.solid_capstyle: projecting
lines.solid_joinstyle: round
markers.fillstyle: full
mathtext.bf: sans:bold
mathtext.cal: cursive
mathtext.default: it
mathtext.fallback_to_cm: true
mathtext.fontset: dejavusans
mathtext.it: sans:italic
mathtext.rm: sans
mathtext.sf: sans
mathtext.tt: monospace
patch.antialiased: true
patch.edgecolor: white
patch.facecolor: C0
patch.force_edgecolor: false
patch.linewidth: 1.0
path.effects: []
path.simplify: true
path.simplify_threshold: 0.1111111111111111
path.sketch: null
path.snap: true
pdf.compression: 6
pdf.fonttype: 3
pdf.inheritcolor: false
pdf.use14corefonts: false
pgf.debug: false
pgf.preamble: []
pgf.rcfonts: true
pgf.texsystem: xelatex
polaraxes.grid: true
ps.distiller.res: 6000
ps.fonttype: 3
ps.papersize: letter
ps.useafm: false
ps.usedistiller: false
savefig.bbox: null
savefig.directory: '~'
savefig.dpi: 300.0
savefig.edgecolor: black
savefig.facecolor: '#212121'
savefig.format: png
savefig.frameon: true
savefig.jpeg_quality: 95
savefig.orientation: portrait
savefig.pad_inches: 0.1
savefig.transparent: false
scatter.marker: o
svg.fonttype: path
svg.hashsalt: null
svg.image_inline: true
text.antialiased: true
text.color: white
text.hinting: auto
text.hinting_factor: 8
text.latex.preamble: []
text.latex.preview: false
text.latex.unicode: false
text.usetex: false
timezone: UTC
tk.window_focus: false
toolbar: toolbar2
verbose.fileo: sys.stdout
verbose.level: silent
webagg.address: 127.0.0.1
webagg.open_in_browser: true
webagg.port: 8988
webagg.port_retries: 50
xtick.alignment: center
xtick.bottom: true
xtick.color: white
xtick.direction: out
xtick.labelbottom: true
xtick.labelsize: medium
xtick.labeltop: false
xtick.major.bottom: true
xtick.major.pad: 3.5
xtick.major.size: 3.5
xtick.major.top: true
xtick.major.width: 0.8
xtick.minor.bottom: true
xtick.minor.pad: 3.4
xtick.minor.size: 2.0
xtick.minor.top: true
xtick.minor.visible: false
xtick.minor.width: 0.6
xtick.top: false
ytick.alignment: center_baseline
ytick.color: white
ytick.direction: out
ytick.labelleft: true
ytick.labelright: false
ytick.labelsize: medium
ytick.left: true
ytick.major.left: true
ytick.major.pad: 3.5
ytick.major.right: true
ytick.major.size: 3.5
ytick.major.width: 0.8
ytick.minor.left: true
ytick.minor.pad: 3.4
ytick.minor.right: true
ytick.minor.size: 2.0
ytick.minor.visible: false
ytick.minor.width: 0.6
ytick.right: false
