axes.facecolor: 212121
figure.facecolor: 212121
figure.dpi: 120
font.size: 12.0
image.cmap: mako
image.aspect: auto
hist.bins: 20
legend.frameon: false
savefig.facecolor: 212121
savefig.dpi: 300
font.family: serif
pdf.fonttype: 42
ps.usedistiller: xpdf

