#!/bin/bash
#SBATCH --job-name=jupyter
#SBATCH --output=jupyter_%j.log
#SBATCH --partition=debug
#SBATCH -c 16
#SBATCH -n 1
#SBATCH --mem=100GB
#SBATCH --time=2-00:00:00

date;hostname;pwd

unset XDG_RUNTIME_DIR

port=$(shuf -i 20000-30000 -n 1)

echo -e "\nStarting Jupyter labe on port ${port} on the $(hostname) server."
echo -e "\nSSH tunnel command: ssh -NL ${port}:localhost:${port} ${USER}@$(hostname)"
echo -e "\nLocal URI: http://localhost:${port}"
jupyter lab --no-browser --port=${port} --ip="0.0.0.0"

date
