#!/bin/bash

# use like so:
# orchid -f -u wg41 -n mezzanine

node="orchestra"
X11=""
forward=""
sshcmd=".med.harvard.edu"
showhelp=""
user="wg41"
helptxt="
-n: which orchestra node
-X: X11 forwarding
-f: port forward to localhost:8989
"

while getopts 'u:hXfn:' flag; do
	case "${flag}" in
		u) user="${OPTARG}" ;;
		n) node="${OPTARG}" ;;
		X) X11=true ;;
		f) forward=true ;;
		h) showhelp=true ;;
		*) echo "Unexpected flag ${flag}" ;;
	esac
done

if [ $showhelp ]
then
	echo "${helptxt}"
	exit 0
fi

sshcmd="${user}@${node}${sshcmd}"
if [ $X11 ]
then
	sshcmd="-Y ${sshcmd}"
fi

if [ $forward ]
then
	sshcmd="-L 8989:localhost:8989 ${sshcmd}"
fi

eval "ssh $sshcmd"
