#!/bin/bash

# run like so in another window
# port-forward -n clarinet001-062

node="clarinet001-062"
port="8989"
o2=""
verbose=""
address="orchestra"

while getopts "vn:p:2" flag; do
  case "${flag}" in
    n) node="${OPTARG}" ;;
    p) port="${OPTARG}" ;;
    2) o2=true;;
    v) verbose=true;;
    *) echo "don't understand" ;;
  esac
done

if [ $o2 ]; then
  address="o2.rc.hms.harvard.edu"
fi

cmd="ssh -L ${port}:localhost:${port} ${node}.${address}"

if [ $verbose ]; then
  echo ${cmd}
else
  eval ${cmd}
fi
