#!/bin/bash

infile="mouse-extract.h5"
outfile="arhmm-single-trans.model"
ncpu="8"
iterations="500"
verbose=""

while getopts "i:f:o:n:v" flag; do
  case "${flag}" in
    f) infile="${OPTARG}";;
    o) outfile="${OPTARG}";;
    n) ncpu="${OPTARG}";;
    v) verbose=true;;
    i) iterations="${OPTARG}";;
    *) echo "Fuck you you piece of shit";;
  esac
done

if [ ${verbose} ]; then
  echo moseq train-arhmm "${infile}" --out-file "${outfile}" --n-cpu "${ncpu}" --iterations "${iterations}"
else
  moseq train-arhmm "${infile}" --out-file "${outfile}" --n-cpu "${ncpu}" --iterations "${iterations}"
fi
