#!/bin/bash

infile="mouse-extract.h5"
dimension="20"
ncpu="8"
dataname="images"

while getopts "f:d:n:" flag; do
  case "${flag}" in
    f) infile="${OPTARG}";;
    d) dimension="${OPTARG}";;
    n) ncpu="${OPTARG}";;
    *) echo "Fuck you you piece of shit";;
  esac
done

moseq train-pca "${infile}" --dimension "${dimension}" --raw-data-name "${dataname}" --n-cpu "${ncpu}"
