#!/bin/bash
# my version of (interactive) srun to make some things easy on me

mem="4G"
partition="interactive"
interactive=""
ncpu="1"
shell="zsh"
x11=""
cmd="echo 'there does not seem to be anything here'"


while getopts 'im:n:s:x' flag; do
  case "${flag}" in
    i) interactive=true;;
    m) mem="${OPTARG}";;
    n) ncpu="$OPTARG";;
		x) x11=true;;
    s) shell="${OPTARG}";;
    *) echo "what the fuck willis what the fuck you doin to me";;
  esac
done

cmd="srun -n ${ncpu} -t 12:00:00 --mem=${mem} -p ${partition}"

if [ $interactive ]; then
  cmd="${cmd} --pty"
fi

if [ $x11 ]; then
	cmd="${cmd} --x11"
fi

echo "${cmd} ${shell}"
eval "${cmd} ${shell}"
